som_deep_informer_big:
  output_mode: default
  redshift_col: &id013 specz
  hdf5_groupname: None
  nproc: 128
  inputs: &id002
  - flux_pgauss_LSST_u
  - flux_pgauss_LSST_g
  - flux_pgauss_LSST_r
  - flux_pgauss_LSST_i
  - flux_pgauss_LSST_z
  - flux_pgauss_LSST_y 
  - flux_pgauss_Y
  - flux_pgauss_J
  - flux_pgauss_H
  input_errs: &id003
  - flux_err_pgauss_LSST_u
  - flux_err_pgauss_LSST_g
  - flux_err_pgauss_LSST_r
  - flux_err_pgauss_LSST_i
  - flux_err_pgauss_LSST_z
  - flux_err_pgauss_LSST_y 
  - flux_err_pgauss_Y
  - flux_err_pgauss_J
  - flux_err_pgauss_H
  zero_points: &id004
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5  
  som_shape: &id005 [64, 64]
  som_minerror: 0.01
  som_wrap: &id016 false
  som_take_log: &id015 True
  convert_to_flux: &id014 false
  set_threshold: true
  thresh_val: 1.0e-05
  thresh_val_err: 1.0e-05
  name: som_deep_informer_big
  model: out/model_deep.pkl
  som_takelog: false
  config: None
som_wide_informer_big:
  output_mode: default
  redshift_col: *id013
  hdf5_groupname: None
  nproc: 128
  inputs: &id006
  - flux_pgauss_LSST_u
  - flux_pgauss_LSST_g
  - flux_pgauss_LSST_r
  - flux_pgauss_LSST_i
  - flux_pgauss_LSST_z
  - flux_pgauss_LSST_y 
  - flux_pgauss_Y
  - flux_pgauss_J
  - flux_pgauss_H
  input_errs: &id007
  - flux_err_pgauss_LSST_u
  - flux_err_pgauss_LSST_g
  - flux_err_pgauss_LSST_r
  - flux_err_pgauss_LSST_i
  - flux_err_pgauss_LSST_z
  - flux_err_pgauss_LSST_y 
  - flux_err_pgauss_Y
  - flux_err_pgauss_J
  - flux_err_pgauss_H
  zero_points: &id008
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5  

  som_shape: &id009 [32, 32]
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  thresh_val_err: 1.0e-05
  name: som_wide_informer_big
  model: out/model_wide.pkl
  som_takelog: false
  config: None


som_deepdeep_estimator:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: &id011 5.0
  nzbins: &id012 501
  calculated_point_estimates: &id001 []
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id002
  input_errs: *id003
  zero_points: *id004
  som_shape: *id005
  som_minerror: 0.01
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_deepdeep_estimator
  model: out/model_deep.pkl
  assignment: out/deepdata_deep_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None
som_deepwide_estimator:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id006
  input_errs: *id007
  zero_points: *id008
  som_shape: *id009
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_deepwide_estimator
  model: out/model_wide.pkl
  assignment: out/deepdata_wide_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None
som_deepspec_estimator:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id002
  input_errs: *id003
  zero_points: *id004
  som_shape: *id005
  som_minerror: 0.01
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_deepspec_estimator
  model: out/model_deep.pkl
  thresh_val_err: 1.0e-05
  config: None
  assignment: out/deepspecdata_deep_assignment.hdf5
som_widewide_estimator:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: *id011
  zmax: *id012
  nzbins: 301
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id006
  input_errs: *id007
  zero_points: *id008
  som_shape: *id009
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_widewide_estimator
  model: out/model_wide.pkl
  assignment: out/widedata_wide_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None
som_widespec_estimator:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id006
  input_errs: *id007
  zero_points: *id008
  som_shape: *id009
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_widespec_estimator
  model: out/model_wide.pkl
  assignment: out/specdata_wide_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None
som_pzc_stage:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: &id010
  - MAG_U
  - MAG_G
  - MAG_R
  - MAG_I
  - MAG_Z
  redshift_col: *id013
  deep_groupname: None
  bin_edges:
  - 0.0
  - 0.35
  - 0.65
  - 0.85
  - 2.0
  zbins_min: 0.0
  zbins_max: 3.2
  zbins_dz: 0.02
  name: som_pzc_stage
  pz_c: out/pz_c.hdf5
  config: None
pcchat_stage:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: *id010
  name: pcchat_stage
  deep_som_size: 4096
  wide_som_size: 1024
  redshift_col: *id013
  config: None
sompz_pzchat:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: *id010
  redshift_col: *id013
  bin_edges:
  - 0.0
  - 0.35
  - 0.65
  - 0.85
  - 2.0
  zbins_min: 0.0
  zbins_max: 3.0
  zbins_dz: 0.025
  name: sompz_pzchat
  config: None
sompz_tomobin:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: *id010
  redshift_col: *id013
  bin_edges:
  - 0.0
  - 0.35
  - 0.65
  - 0.85
  - 2.0
  zbins_min: 0.0
  zbins_max: 3.0
  zbins_dz: 0.025
  name: sompz_tomobin
  wide_som_size: 1024
  deep_som_size: 4096
  tomo_bins_wide: tomo_bins_wide.hdf5
  config: None
sompz_nz:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: *id010
  redshift_col: *id013
  bin_edges:
  - 0.0
  - 0.35
  - 0.65
  - 0.85
  - 2.0
  zbins_min: 0.0
  zbins_max: *id011
  zbins_dz: 0.025
  name: sompz_nz
  wide_som_size: 625
  deep_som_size: 1024
  nz: FINAL_NZ.hdf5
  config: None
PhotozDeepZeroPointPipe:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id006
  input_errs: *id007
  zero_points: *id008
  som_shape: *id005
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: PhotozDeepZeroPointPipe
  deep_model: out/model_deep.pkl
  assignment: out/deepdata_zeropoint_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None

